### ISSUE TITLE
Example of adding "String"

### ISSUE THREAD

**Issue by chaoxi24** [UpsettingBoy/typed_shmem#5]
I tried to modify the example, "sh::ShMemCfg::<String>::default()", but it did not work correctly.
Can you add more examples?
For example String/Array/struct

**Comment by jeronimosg** [comment]
Whatever the type you are using for the shared memory must implement zerocopy::AsBytes and zerocopy::FromBytes. Here is a detailed list of all the types that can be used out of the box: [https://docs.rs/zerocopy/0.4.0/zerocopy/trait.AsBytes.html](https://docs.rs/zerocopy/0.4.0/zerocopy/trait.AsBytes.html).

String doesn't implement them, so the solution is to copy the data into a byte buffer and share it.
Keep in mind that with this solution you must ensure the data format on both reads and writes.

**Comment by chaoxi24** [comment]
Thank you. 
I used a simpler solution to write strings.

```
fn main() {
	let t = "asdfg".to_string();
	unsafe {
		cfm_set("T1", t.as_ptr(), t.len());
	}

	let (tx, rx) = std::sync::mpsc::channel();
	let t: u32 = rx.recv().unwrap();
}

unsafe fn cfm_set(name: &'static str, ptr: *const u8, size: usize) {
	extern "system" {
		fn OpenFileMappingW(hFile: u32, dwFlags: bool, lpLibFileName: *const u16) -> u32;
		fn MapViewOfFile(a: u32, b: u32, c: u32, d: u32, e: usize) -> u64;
		fn UnmapViewOfFile(e: u64) -> u32;
		fn RtlMoveMemory(a: u64, b: *const u8, c: usize);
		fn CreateFileMappingW(a: i64, b: u32, c: u32, d: u32, e: u32, Name: *const u16) -> u32;
	}
	let sz = size as u32;
	let nm: Vec<u16> = name.encode_utf16().chain(Some(0)).collect();
	let cf = CreateFileMappingW(-1, 0, 4, sz >> 16 >> 16, sz & 0xffffffff, nm.as_ptr());
	let mf = MapViewOfFile(cf, 2, 0, 0, 0);
	RtlMoveMemory(mf, ptr, size);
	UnmapViewOfFile(mf);
}
